name: 'Execute Attribute Liner'
description: 'Lint your projects attributes.'

inputs:
  target-path:
    description: 'The path the linter is checking'
    default: "./"
  project-alias:
    description: 'Project alias used in "data-fti-xx-" attributes'
    required: true
  ignore-hidden:
    description: 'Ignore all files and directories that are hidden'
    default: "true"
  forbid-data-id:
    description: 'Forbid the use of the data-id attribute'
    default: "true"
  exit-on-violation:
    description: 'Exit with code 1 when finding any violations'
    default: "true"
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 21
        cache: gradle
    - name: Execute Linter
      shell: bash
      run: |
        ./gradlew run --args=" \
          --target-path $TARGET_PATH \
          --project-alias $PROJECT_ALIAS \
          --ignore-hidden $IGNORE_HIDDEN \
          --forbid-data-id $FORBID_DATA_ID \
          --exit-on-violation $EXIT_ON_VIOLATION \
        "
      env:
        TARGET_PATH: ${{ inputs.target-path }}
        PROJECT_ALIAS: ${{ inputs.project-alias }}
        IGNORE_HIDDEN: ${{ inputs.ignore-hidden }}
        FORBID_DATA_ID: ${{ inputs.forbid-data-id }}
        EXIT_ON_VIOLATION: ${{ inputs.exit-on-violation }}
        CI: true
    - run: echo ${{ inputs }}
      shell: bash