on:
  push:
    branches: [ main ]
    branches-ignore:
      - README.md

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ../../action.yml
        with:
          project-alias: 'ci'
